<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-OC9VCOAV" failures="1" tests="1" name="Default test" time="0.046" errors="0" timestamp="27 Apr 2022 07:16:22 GMT">
  <testcase classname="com.ecommerce.testcases.LoginPageTest" name="loginTest" time="0.0">
    <failure type="org.testng.TestNGException" message="
Method public void com.ecommerce.testcases.LoginPageTest.loginTest(java.lang.String,java.lang.String) throws java.lang.Throwable requires a @DataProvider named : credentials in class org.testng.annotations.DataProvider">
      <![CDATA[org.testng.TestNGException: Method public void com.ecommerce.testcases.LoginPageTest.loginTest(java.lang.String,java.lang.String) throws java.lang.Throwable requires a @DataProvider named : credentials in class org.testng.annotations.DataProviderat org.testng.internal.Parameters.findDataProvider(Parameters.java:513)at org.testng.internal.Parameters.handleParameters(Parameters.java:691)at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:914)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- loginTest -->
</testsuite> <!-- Default test -->
